---
title: "Projeto Final FIP606"
author: "Gabriel A D Serafini e Lucas R Versari"
---


# Cálculo MGi
```{r}
library(readxl)
dados <- read_excel("SensibilidadeCory2020.xlsx")
head(dados)
```

```{r}
library(dplyr)

dados |> 
    group_by(trat, dose, aval, isolado) |> 
    summarize(mean_value = mean(valor)) |> 
    ungroup()

```

```{r}
# Médias
medias <- dados |> 
  group_by(trat,dose, aval, isolado) |> 
  summarize(media_diam = mean(diam)) |> 
  ungroup()
calcular_mgi <- function(dados) {
  dados <- dados |> 
    mutate(dose = as.numeric(dose),
           diam = as.numeric(diam),
           aval = as.factor(aval),
           rep = as.factor(rep)) 
  MDc <- dados |> 
    filter(dose == 0) |> 
    group_by(trat, isolado, aval) |> 
    summarize(MDc = mean(diam, na.rm = TRUE), .groups = 'drop')
  dados_com_mdc <- dados %>%
    left_join(MDc, by = c("trat", "isolado", "aval"))
  dados_com_mgi <- dados_com_mdc %>%
    mutate(MGi = if_else(dose == 0, NA_real_, (MDc - diam) / MDc * 100))
  
  return(dados_com_mgi)
}

resultados_mgi <- calcular_mgi(dados)
head(resultados_mgi)
```





MODELOS DE REGRESSÃO - USANDO DIAM

Tratamento
